name: e20-prova

## All Services
services:
  ## ------------------------------------------------------------------------------- Prerequisites
  ## Vault
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    hostname: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN_DOCKER}
      - VAULT_DEV_LISTEN_ADDRESS=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: sh -c "vault server -dev -dev-root-token-id=root -dev-listen-address=0.0.0.0:8200 & sleep 5 && sh /vault/init-vault.sh && wait"
    volumes:
      ## Vault Secrets
      - ./docker-setup/vault/secrets/secrets-application.json:/vault/config/secrets-application.json
      - ./docker-setup/vault/secrets/secrets-autenticazione.json:/vault/config/secrets-autenticazione.json
      - ./docker-setup/vault/secrets/secrets-certs.json:/vault/config/secrets-certs.json
      - ./docker-setup/vault/secrets/secrets-utente.json:/vault/config/secrets-utente.json
      - ./docker-setup/vault/secrets/secrets-evento.json:/vault/config/secrets-evento.json
      - ./docker-setup/vault/secrets/secrets-ordine.json:/vault/config/secrets-ordine.json
      - ./docker-setup/vault/secrets/secrets-pagamento.json:/vault/config/secrets-pagamento.json
      - ./docker-setup/vault/secrets/secrets-mail.json:/vault/config/secrets-mail.json

      ## Init File
      - ./docker-setup/vault/init-vault.sh:/vault/init-vault.sh
    healthcheck:
      test: [ "CMD-SHELL", "vault status -address=http://127.0.0.1:8200 >/dev/null 2>&1" ]
      interval: 5s
      timeout: 5s
      retries: 10

  ## ------------------------------------------------------------------------------- Basic
  ## Discovery Service
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    hostname: discovery-service
    ports:
      - "8061:8061"
    environment:
      - SERVER_PORT=8061
    healthcheck:
      test: [ "CMD", "wget","--spider", "--timeout=5", "--quiet", "http://localhost:8061/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ## Configuration Service
  configuration-service:
    build: ./configuration-service
    container_name: configuration-service
    hostname: configuration-service
    expose:
      - "8088"
    volumes:
      - ./configuration-service/src/main/resources/config:/config
    environment:
      ## Default Config
      - SERVER_PORT=8088
      - AUTH_TOKEN_ISSUER=https://${IP_ADDRESS}:9000
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:/config
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--timeout=5", "--quiet", "http://localhost:8088/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ## Authentication Server
  authentication-server:
    build: ./authentication-server
    container_name: authentication-server
    hostname: authentication-server
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - ./certs:/certs
    environment:
      ## Vault Config
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=${VAULT_TOKEN_DOCKER}
      - SPRING_CLOUD_VAULT_APPLICATION_NAME=application,autenticazione,certs

      ## Default Config
      - SERVER_PORT=9000
      - AUTH_TOKEN_ISSUER=https://${IP_ADDRESS}:9000
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8061/eureka/
      - SPRING_SECURITY_OAUTH2_AUTHORIZATIONSERVER_ISSUER=https://${IP_ADDRESS}:9000

      ## Database Info
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/e20-auth

      ## Certificates Config
      - SERVER_SSL_KEY_STORE=/certs/server.p12
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --header='X-Internal-Communication: $INTERNAL_COMMUNICATIONKEY' --spider --timeout=5 --quiet https://localhost:9000/actuator/health --no-check-certificate"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      vault:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      auth-db:
        condition: service_started

  ## ------------------------------------------------------------------------------- Internal Services
  ## Utente Service
  utente-service:
    build: ./utente-service
    container_name: utente-service
    hostname: utente-service
    expose:
      - "8080"
    volumes:
      - ./certs:/certs
      - ./docker-setup/import-cert.sh:/docker-entrypoint-init.d/import-cert.sh
    entrypoint: [ "/bin/sh", "-c", "/docker-entrypoint-init.d/import-cert.sh && java -jar /app/app.jar" ]
    environment:
      ## Vault Config
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=${VAULT_TOKEN_DOCKER}
      - SPRING_CLOUD_VAULT_APPLICATION_NAME=application,utente

      ## Default Config
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8061/eureka/
      - CONFIG_SERVER_URL=http://configuration-service:8088

      ## Database Info
      - SPRING_DATASOURCE_URL=jdbc:postgresql://utente-db:5432/e20-utenti
    depends_on:
      vault:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      configuration-service:
        condition: service_healthy
      authentication-server:
        condition: service_healthy
      utente-db:
        condition: service_started

  ## Evento Location Service
  evento-location-service:
    build: ./eventoLocation-service
    container_name: eventoLocation-service
    hostname: eventoLocation-service
    expose:
      - "8080"
    volumes:
      - ./certs:/certs
      - ./docker-setup/import-cert.sh:/docker-entrypoint-init.d/import-cert.sh
    entrypoint: [ "/bin/sh", "-c", "/docker-entrypoint-init.d/import-cert.sh && java -jar /app/app.jar" ]
    environment:
      ## Vault Config
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=${VAULT_TOKEN_DOCKER}
      - SPRING_CLOUD_VAULT_APPLICATION_NAME=application,evento

      ## Default Config
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8061/eureka/
      - CONFIG_SERVER_URL=http://configuration-service:8088

      ## Database Info
      - SPRING_DATASOURCE_URL=jdbc:postgresql://eventoLocation-db:5432/e20-eventi
    depends_on:
      vault:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      configuration-service:
        condition: service_healthy
      authentication-server:
        condition: service_healthy
      eventoLocation-db:
        condition: service_started

  ## Gestione Ordini Service
  gestione-ordini-service:
    build: ./gestioneOrdini-service
    container_name: gestioneOrdini-service
    hostname: gestioneOrdini-service
    expose:
      - "8080"
    volumes:
      - ./certs:/certs
      - ./docker-setup/import-cert.sh:/docker-entrypoint-init.d/import-cert.sh
    entrypoint: [ "/bin/sh", "-c", "/docker-entrypoint-init.d/import-cert.sh && java -jar /app/app.jar" ]
    environment:
      ## Vault Config
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=${VAULT_TOKEN_DOCKER}
      - SPRING_CLOUD_VAULT_APPLICATION_NAME=application,ordine

      ## Default Config
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8061/eureka/
      - CONFIG_SERVER_URL=http://configuration-service:8088

      ## Database Info
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gestioneOrdini-db:5432/e20-ordini
    depends_on:
      vault:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      configuration-service:
        condition: service_healthy
      authentication-server:
        condition: service_healthy
      gestioneOrdini-db:
        condition: service_started

  ## Payment Service
  payment-service:
    build: ./payment-service
    container_name: payment-service
    hostname: payment-service
    expose:
      - "8080"
    volumes:
      - ./certs:/certs
      - ./docker-setup/import-cert.sh:/docker-entrypoint-init.d/import-cert.sh
    entrypoint: [ "/bin/sh", "-c", "/docker-entrypoint-init.d/import-cert.sh && java -jar /app/app.jar" ]
    environment:
      ## Vault Config
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=${VAULT_TOKEN_DOCKER}
      - SPRING_CLOUD_VAULT_APPLICATION_NAME=application,pagamento

      ## Default Config
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8061/eureka/
      - CONFIG_SERVER_URL=http://configuration-service:8088

      ## Database Info
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payment-db:5432/e20-pagamenti
    depends_on:
      vault:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      configuration-service:
        condition: service_healthy
      authentication-server:
        condition: service_healthy
      payment-db:
        condition: service_started

  ## Mail Sender Service
  mail-sender-service:
    build: ./mailSender-service
    container_name: mailSender-service
    hostname: mailSender-service
    expose:
      - "8080"
    volumes:
      - ./certs:/certs
      - ./docker-setup/import-cert.sh:/docker-entrypoint-init.d/import-cert.sh
    entrypoint: [ "/bin/sh", "-c", "/docker-entrypoint-init.d/import-cert.sh && java -jar /app/app.jar" ]
    environment:
      ## Vault Config
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=${VAULT_TOKEN_DOCKER}
      - SPRING_CLOUD_VAULT_APPLICATION_NAME=application,mail

      ## Default Config
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8061/eureka/
      - CONFIG_SERVER_URL=http://configuration-service:8088

    depends_on:
      vault:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      configuration-service:
        condition: service_healthy
      authentication-server:
        condition: service_healthy

  ## ------------------------------------------------------------------------------- Gateway
  ## Gateway Service
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    hostname: gateway-service
    ports:
      - "8060:8060"
    volumes:
      - ./certs:/certs
      - ./docker-setup/import-cert.sh:/docker-entrypoint-init.d/import-cert.sh
    entrypoint: [ "/bin/sh", "-c", "/docker-entrypoint-init.d/import-cert.sh && java -jar /app/app.jar" ]
    environment:
      ## Vault Config
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=${VAULT_TOKEN_DOCKER}
      - SPRING_CLOUD_VAULT_APPLICATION_NAME=application,certs

      ## Default Config
      - SERVER_PORT=8060
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8061/eureka/
      - CONFIG_SERVER_URL=http://configuration-service:8088

      ## Certification Config
      - SERVER_SSL_KEY_STORE=/certs/server.p12
    depends_on:
      vault:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      configuration-service:
        condition: service_healthy
      authentication-server:
        condition: service_healthy
      utente-service:
        condition: service_started
      evento-location-service:
        condition: service_started
      gestione-ordini-service:
        condition: service_started
      payment-service:
        condition: service_started
      mail-sender-service:
        condition: service_started

  ## ------------------------------------------------------------------------------- Databases
  ## Authentication Server DB
  auth-db:
    image: postgres:16
    container_name: auth-db
    restart: always
    environment:
      - POSTGRES_DB=e20-auth
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_password
    ports:
      - "5432:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data

  ## Utente Service DB
  utente-db:
    image: postgres:16
    container_name: utente-db
    restart: always
    environment:
      - POSTGRES_DB=e20-utenti
      - POSTGRES_USER=utenti_user
      - POSTGRES_PASSWORD=utenti_password
    ports:
      - "5433:5432"
    volumes:
      - utente_data:/var/lib/postgresql/data

  ## Evento Location Service DB
  eventoLocation-db:
    image: postgres:16
    container_name: eventoLocation-db
    restart: always
    environment:
      - POSTGRES_DB=e20-eventi
      - POSTGRES_USER=eventi_user
      - POSTGRES_PASSWORD=eventi_password
    ports:
      - "5434:5432"
    volumes:
      - eventoLocation_data:/var/lib/postgresql/data

  ## Gestione Ordini Service DB
  gestioneOrdini-db:
    image: postgres:16
    container_name: gestioneOrdini-db
    restart: always
    environment:
      - POSTGRES_DB=e20-ordini
      - POSTGRES_USER=ordini_user
      - POSTGRES_PASSWORD=ordini_password
    ports:
      - "5435:5432"
    volumes:
      - gestioneOrdini_data:/var/lib/postgresql/data

  ## Payment Service DB
  payment-db:
    image: postgres:16
    container_name: payment-db
    restart: always
    environment:
      - POSTGRES_DB=e20-pagamenti
      - POSTGRES_USER=pagamenti_user
      - POSTGRES_PASSWORD=pagamenti_password
    ports:
      - "5436:5432"
    volumes:
      - payment_data:/var/lib/postgresql/data

## Volumes for Databases
volumes:
  auth_data:
  utente_data:
  eventoLocation_data:
  gestioneOrdini_data:
  payment_data: