server:
  port: 0

spring:
  application:
    name: mailSender-service
  config:
    import: configserver:http://localhost:8088
  cloud:
    vault:
      uri: https://127.0.0.1:8200
      ssl:
        trust-store: classpath:ca.jks
        trust-store-password: ${TRUST_STORE_PASSWORD}
      authentication: approle
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
      kv:
        enabled: true
        backend: secret
        default-context: mail_credentials
mail:
  username: ${username}
  password: ${password}
springdoc:
  packages-to-scan: org.unical.enterprise.mailSender-service