server:
  port: 8088

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: ${HOME}/config

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,refresh
        exclude: env,configprops

  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  prometheus:
    metrics:
      export:
        enabled: true