server:
  port: 8080

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: ${HOME}/config

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/esse20

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,refresh
        exclude: env,configprops

  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  prometheus:
    metrics:
      export:
        enabled: true