server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store-password: ${KS_PWD}
    key-password: ${KEY_PWD}
    key-store: classpath:keystore.p12
  max-http-request-header-size: 48KB # Aumenta la dimensione massima dell'header HTTP

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8080