spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:https://localhost:8441"
  cloud:
    gateway:
      globalcors:
        cors-configurations:
            '[/**]':
                allowed-origins: 'http://localhost:8060'
                allowed-methods: '*'
                allowed-headers: '*'
                allow-credentials: true
                max-age: 3600
  output:
    ansi:
      enabled: always

eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:8442/eureka/

server:
  ssl:
    enabled: true
    key-store: classpath:esse20.p12
    key-store-type: PKCS12
    key-store-password: eaproject
    key-alias: esse20
    key-password: eaproject
  port: 8443
  max-http-request-header-size: 48KB # Aumenta la dimensione massima dell'header HTTP

rate-limiter:
  permits-per-second: 5
