server:
  port: 8443
  ssl:
    key-store: classpath:esse20.p12
    key-store-type: PKCS12
    key-store-password: ${keystore_password}
    key-alias: esse20
    key-password: ${key_password}
  max-http-request-header-size: 48KB # Aumenta la dimensione massima dell'header HTTP

spring:
  application:
    name: gateway-service
  config:
    import: configserver:http://localhost:8088