server:
  port: 8443
  ssl:
    key-store: classpath:esse20.p12
    key-store-type: PKCS12
    key-store-password: eaproject
    key-alias: esse20
    key-password: eaproject
  max-http-request-header-size: 48KB # Aumenta la dimensione massima dell'header HTTP

spring:
  application:
    name: gateway-service
  config:
    import: configserver:http://localhost:8088
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "http://localhost:3000"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
                allow-credentials: true
                max-age: 3600

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8061/eureka/
  instance:
    hostname: localhost

rate-limiter:
  permits-per-second: 5