spring:
  application:
    name: payment-service
  cloud:
    vault:
      token: ${VAULT_TOKEN}
      uri: ${VAULT_ADDR}
      application-name: application

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
    mode: HTML

  config:
    import:
      - "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8088}"
      - "optional:file:.env[.properties]"
      - "vault://"