server:
  port: 0

spring:
  application:
    name: utente-service
  datasource:
    username: ${username}
    password: ${password}
  config:
    import:
      - "configserver:http://localhost:8080"
      - "vault://"

  # database fallback che viene sostituito una volta caricata la configurazione
#  datasource:
#    url: jdbc:h2:mem:tempdb
#    driver-class-name: org.h2.Driver

  cloud:
    config:
      fail-fast: true
    vault:
      uri: https://127.0.0.1:8200
      ssl:
        trust-store: classpath:ca.jks
        trust-store-password: ${TRUST_STORE_PASSWORD}
      authentication: approle
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
      kv:
        enabled: true
        backend: secret
        default-context: e20


jwt:
  secret: ${jwt.secret}
  security:
    enabled: false