server:
  port: 0

spring:
  application:
    name: utente-service
  datasource:
    username: ${username}
    password: ${password}
    url: jdbc:postgresql://localhost:5454/e20

  config:
    import:
      - "optional:configserver:http://localhost:8088"
      - "vault://"
  cloud:
    vault:
      uri: https://127.0.0.1:8200
      ssl:
        trust-store: classpath:ca.jks
        trust-store-password: ${TRUST_STORE_PASSWORD}
      authentication: approle
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
      kv:
        enabled: true
        backend: secret
        default-context: ${spring.application.name}

  jpa:
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      client:
        registration:
          gateway-client:
            client-id: gateway-client
        provider:
          gateway-client:
            issuer-uri: http://127.0.0.1:9000
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
      fetch-registry: true
      register-with-eureka: true
      lease-renewal-interval-in-seconds: 10
      lease-expiration-duration-in-seconds: 30


jwt:
  security:
    enabled: true
    publicPaths: /v3/api-docs/**, /swagger-ui/**, /swagger-ui.html, /api/utente/register, /api/utente/test
    protectedRoutes:
      - path: /api/utente
        roles:
          - ROLE_ADMIN
      - path: /api/utente/{username}
        roles:
          - ROLE_USER
      - path: DELETE:/api/utente/{username}
        roles:
          - ROLE_USER
      - path: PUT:/api/utente/{username}
        roles:
          - ROLE_USER
      - path: /api/utente/getById
        roles:
          - ROLE_ADMIN