server:
  port: 0

spring:
  application:
    name: utente-service
  datasource:
    username: ${username}
    password: ${password}
    url: jdbc:postgresql://localhost:5454/e20
  config:
    import:
      - "configserver:http://localhost:8088"
      - "vault://"
  cloud:
    config:
      fail-fast: true
    vault:
      uri: https://127.0.0.1:8200
      ssl:
        trust-store: classpath:ca.jks
        trust-store-password: ${TRUST_STORE_PASSWORD}
      authentication: approle
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
      kv:
        enabled: true
        backend: secret
        default-context: ${spring.application.name}

jwt:
  secret: ${jwt.secret}
  security:
    enabled: false