spring:
  application:
    name: utente-service
  config:
    import: "optional:configserver:https://localhost:8441"
  cloud:
    config:
      uri: http://localhost:8088
      fail-fast: true
  output:
    ansi:
      enabled: always

eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:8442/eureka/

jwt:
  secret: ZNAUhywjWMxENUeQvxjmDSfbNHaJeYmecN4pGHgZxQMqgdHZGLNejvtP9PuXCmE6 # si potrebbe centrallizare inserirela in un punto comume o costante in SHARED o variabile di sistema
  security:
    enabled: true
    publicPaths: /v3/api-docs/**, /swagger-ui/**, /swagger-ui.html, /api/**

server:
  ssl:
    enabled: true
    key-store: classpath:esse20.p12
    key-store-type: PKCS12
    key-store-password: eaproject
    key-alias: esse20
    key-password: eaproject
  port: 0