spring:
  application:
    name: utente-service
  cloud:
    vault:
      token: ${VAULT_TOKEN}
      uri: ${VAULT_ADDR}
      application-name: application

  config:
    import:
      - "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8088}"
      - "optional:file:.env[.properties]"
      - "vault://"

server:
  port: 0