
## Logging
logging:
  level:
    org.springframework.security.oauth2.server.resource.authentication: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.security.authentication: DEBUG


## Common Token Properties
auth:
  token:
    issuer: "http://127.0.0.1:9000"
    expiration: 3600
    secret: "mS6QTX_6tt-JAhJTf5VzgY_XrKfLbEC4LLMBj8B02R8"
