spring:
  security:
    oauth2:
      client:
        registration:
          gateway-client:
            client-id: gateway-client
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8060/login/oauth2/code/gateway-client
            scope: openid, profile

        provider:
          gateway-client:
            issuer-uri: http://127.0.0.1:9000
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000

logging:
  level:
    org.springframework.security.oauth2.server.resource.authentication: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.security.authentication: DEBUG
