spring:
  security:
    oauth2:
      client:
        registration:
          custom-oidc:
            client-id: oidc-client
            client-secret: secret
            scope:
              - openid
              - profile
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8060/login/oauth2/code/custom-oidc
        provider:
          custom-oidc:
            #usare 127.0.0.1
            issuer-uri: http://127.0.0.1:9000  # Sostituisci con il tuo issuer URL
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000

logging:
  level:
    org.springframework.security.oauth2.server.resource.authentication: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.security.authentication: DEBUG