spring:
  security:
    oauth2: ## OAuth2 Clients
      client:
        registration:
          gateway-client:
            client-id: gateway-client
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://192.168.1.14:8060/login/oauth2/code/gateway-client
            scope: openid, profile

        provider:
          gateway-client:
            issuer-uri: ${auth.token.issuer}
      resourceserver:
        jwt:
          issuer-uri: ${auth.token.issuer}


## Logging
logging:
  level:
    org.springframework.security.oauth2.server.resource.authentication: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.security.authentication: DEBUG


## Common Token Properties
auth:
  token:
    issuer: "http://192.168.1.14:9000"
    expiration: 3600
