spring:
  application:
    name: eventoLocation-service
  output:
    ansi:
      enabled: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

cors:
  allowed-origins: http://localhost:8060

jwt:
  security:
    enabled: true
    publicPaths:
      /v3/api-docs/**,
      /swagger-ui/**,
      /swagger-ui.html,
      /api/evento/{id} ,
      /api/evento ,
      /api/evento/test,
      /api/location,
      /api/location/{id},
      /api/location/test,
      /api/preferiti/test
    protectedRoutes:
      - path: /api/preferiti/**
        roles:
          - ROLE_USER
      - path: /api/evento
        roles:
          - ROLE_MANAGER
      - path: /api/evento/DELETE
        roles:
          - ROLE_MANAGER
      - path: /api/evento/PUT
        roles:
          - ROLE_MANAGER
      - path: /api/location/{id}/DElETE
        roles:
          - ROLE_ADMIN
      - path: /api/location/POST
        roles:
          - ROLE_MANAGER
      - path: /api/location/{id}/PUT
        roles:
          - ROLE_MANAGER

springdoc:
  packages-to-scan: org.unical.enterprise.pagamentoBiglietto-service
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true
