eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
    registry-fetch-interval-seconds: 10
    fetch-registry: true


spring:
  output:
    ansi:
      enabled: always

  cloud:
    discovery:
      enabled: true
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: false
      routes:

        ## Autenticazione
        - id: delete-account
          uri: lb://authentication-server
          predicates:
            - Path=/api/utente/me
            - Method=DELETE
        - id: authentication-server
          uri: lb://authentication-server
          predicates:
            - Path=/auth/**

        ## Gestione Oridni
        - id: gestioneOrdini-ordine-service
          uri: lb://gestioneOrdini-service
          predicates:
            - Path=/api/ordine/**
        - id: gestioneOrdini-biglietto-service
          uri: lb://gestioneOrdini-service
          predicates:
            - Path=/api/biglietto/**

        ## Utenti
        - id: utente-service
          uri: lb://utente-service
          predicates:
            - Path=/api/utente/**

        ## Evento Location
        - id: eventoLocation-evento-service
          uri: lb://eventoLocation-service
          predicates:
            - Path=/api/evento/**
        - id: eventoLocation-location-service
          uri: lb://eventoLocation-service
          predicates:
            - Path=/api/location/**
        - id: eventoLocation-preferiti-service
          uri: lb://eventoLocation-service
          predicates:
            - Path=/api/preferiti/**

        ## Mail Sender
        - id: mailSender-service
          uri: lb://mailSender-service
          predicates:
            - Path=/api/token/**

        ## Pagamento
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/stripe/**

        - id: webPage-service
          uri: lb://payment-service
          predicates:
            - Path=/web/**

        # Rotte per Swagger GestioneOrdini Service
        - id: gestioneOrdini-service-api-docs
          uri: lb://gestioneOrdini-service
          predicates:
            - Path=/gestioneOrdini-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: gestioneOrdini-service-swagger-ui
          uri: lb://gestioneOrdini-service
          predicates:
            - Path=/gestioneOrdini-service/swagger-ui/**
          filters:
            - StripPrefix=1

        # Rotte per Swagger Utente Service
        - id: utente-service-api-docs
          uri: lb://utente-service
          predicates:
            - Path=/utente-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: utente-service-swagger-ui
          uri: lb://utente-service
          predicates:
            - Path=/utente-service/swagger-ui/**
          filters:
            - StripPrefix=1

        # Rotte per Swagger EventoLocation Service
        - id: eventoLocation-service-api-docs
          uri: lb://eventoLocation-service
          predicates:
            - Path=/eventoLocation-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: eventoLocation-service-swagger-ui
          uri: lb://eventoLocation-service
          predicates:
            - Path=/eventoLocation-service/swagger-ui/**
          filters:
            - StripPrefix=1

        # Rotte per Swagger MailSender Service
        - id: mailSender-service-api-docs
          uri: lb://mailSender-service
          predicates:
            - Path=/mailSender-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: mailSender-service-swagger-ui
          uri: lb://mailSender-service
          predicates:
            - Path=/mailSender-service/swagger-ui/**
          filters:
            - StripPrefix=1

        # Rotte per Swagger Payment Service
        - id: payment-service-api-docs
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: payment-service-swagger-ui
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/swagger-ui/**
          filters:
            - StripPrefix=1

        ## Rotte per Swagger Authentication Server
        - id: authentication-server-api-docs
          uri: lb://authentication-server
          predicates:
            - Path=/authentication-server/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: authentication-server-swagger-ui
          uri: lb://authentication-server
          predicates:
            - Path=/authentication-server/swagger-ui/**
          filters:
            - StripPrefix=1

springdoc:
  swagger-ui:
    urls:
      - name: Utente Service
        url: /utente-service/v3/api-docs
      - name: Evento-Location Service
        url: /eventoLocation-service/v3/api-docs
      - name: Gestione Ordini Service
        url: /gestioneOrdini-service/v3/api-docs
      - name: Mail Sender Service
        url: /mailSender-service/v3/api-docs
      - name: Payment Service
        url: /payment-service/v3/api-docs
      - name: Authentication Server
        url: /authentication-server/v3/api-docs
