spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: gestioneOrdini-service
              uri: lb://gestioneOrdini-service
              predicates:
                - Path=/api/ordine/**, /api/biglietto/**
            - id: utente-service
              uri: lb://utente-service
              predicates:
                - Path=/api/utente/**
            - id: eventoLocation-service
              uri: lb://eventoLocation-service
              predicates:
                - Path=/api/evento/**, /api/location/**, /api/preferiti/**
            - id: mailSender-service
              uri: lb://mailSender-service
              predicates:
                - Path=/api/mail/**
            - id: authentication-service
              uri: lb://authentication-service
              predicates:
                - Path=/api/authentication/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "http://localhost:3000"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
                allow-credentials: true
                max-age: 3600

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

rate-limiter:
  permits-per-second: 5