spring:
  application:
    name: mailSender-service
  output:
    ansi:
      enabled: always

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

cors:
  allowed-origins: https://localhost:8060

jwt:
  security:
    enabled: true
    publicPaths: /v3/api-docs/**, /swagger-ui/**, /swagger-ui.html, /api/token/**
    protectedRoutes:
      - path: /api/mail/**
        roles:
          - ROLE_ADMIN

logging:
  file:
    name: logs/app.log
  level:
    demacs:
      unical:
        esse20: INFO

springdoc:
  packages-to-scan: org.unical.enterprise.mailSender
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

mail:
  username: ${mail_address}
  password: ${mail_password}