spring:

  security:
    oauth2: ## OAuth2 Clients
      client:
        registration:
          gateway-client:
            client-id: gateway-client
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8060/login/oauth2/code/gateway-client
            scope: openid, profile

        provider:
          gateway-client:
            issuer-uri: ${auth.token.issuer}
      resourceserver:
        jwt:
          issuer-uri: ${auth.token.issuer}

  application:
    name: mailSender-service
  output:
    ansi:
      enabled: always

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

cors:
  allowed-origins: http://localhost:8060

jwt:
  security:
    enabled: true
    publicPaths: /v3/api-docs/**, /swagger-ui/**, /swagger-ui.html, /api/token/**
    protectedRoutes:
      - path: /api/mail/**
        roles:
          - ROLE_ADMIN

logging:
  file:
    name: logs/app.log
  level:
    demacs:
      unical:
        esse20: INFO

springdoc:
  packages-to-scan: org.unical.enterprise.mailSender
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

mail:
  username: noreply.esse20@gmail.com
  password: lqvxdvovovxwmjfd