spring:
  application:
    name: payment-service
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:postgresql://localhost:5454/e20
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

cors:
  allowed-origins: https://localhost:8060

jwt:
  security:
    enabled: true
    publicPaths: /v3/api-docs/**, /swagger-ui/**, /swagger-ui.html, /web/**
    protectedRoutes:
      - path: /api/stripe/**
        roles:
          - ROLE_UTENTE

springdoc:
  packages-to-scan: org.unical.enterprise.payment
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

stripe:
  api:
    secret: ${stripe_secret}
    webhook: ${stripe_webhook}

