spring:
  datasource:
    url: jdbc:postgresql://localhost:5454/e20
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/esse20
          cache-duration: PT5M

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

cors:
  allowed-origins: http://localhost:8060


jwt:
  security:
    enabled: true
    publicPaths: /v3/api-docs/**, /swagger-ui/**, /swagger-ui.html, /api/utente/register, /api/utente/test
    protectedRoutes:
      - path: /api/utente
        roles:
          - ROLE_ADMIN
      - path: /api/utente/{username}
        roles:
          - ROLE_USER
      - path: DELETE:/api/utente/{username}
        roles:
          - ROLE_USER
      - path: PUT:/api/utente/{username}
        roles:
          - ROLE_USER
      - path: /api/utente/getById
        roles:
          - ROLE_ADMIN

logging:
  file:
    name: logs/app.log
  level:
    demacs:
      unical:
        esse20: INFO
      defaultZone: http://localhost:8061/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

springdoc:
  packages-to-scan: org.unical.enterprise.utente
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

