server:
  port: 8061
#  ssl:
#    key-store: classpath:local_ssl.p12
#    key-store-password: changeit
#    key-alias: local_ssl
#    key-store-type: PKCS12
#    enabled: true
#    key-password: changeit

eureka:
  instance:
    hostname: localhost
    secure-port-enabled: true
    non-secure-port-enabled: false
    secure-port: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  cloud:
    config:
      enabled: false
  output:
    ansi:
      enabled: always