
jwt:
  security:
    enabled: true
    publicPaths: /oauth2/**, /.well-known/**, /login, /auth/register


spring:
  application:
    name: authorization-server
  config:
    import: "optional:configserver:http://localhost:8088"
