server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          gateway-client:
            registration:
              client-id: "gateway-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:8060/login/oauth2/code/gateway-client"
              post-logout-redirect-uris:
                - "http://localhost:8060/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
