server:
  port: 9000
  ssl:
    key-store: file:./certs/server.p12
    key-store-password: ${ssl_password}
    key-alias: server
    key-store-type: PKCS12
    enabled: true
    key-password: ${ssl_password}
  address: 0.0.0.0
  forward-headers-strategy: framework


cors:
  allowed-origins: http://localhost:3000, http://localhost:8060

spring:
  config:
    import:
      - "optional:file:.env[.properties]"
      - "vault://"
  cloud:
    vault:
      token: ${VAULT_TOKEN}
      uri: ${VAULT_ADDR}
      application-name: application
    config:
      enabled: false
  application:
    name: authentication-server
  output:
    ansi:
      enabled: always

  ## Database Properties
  datasource:
    url: jdbc:postgresql://localhost:5454/e20
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  ## Security
  security:
    oauth2:
      authorizationserver: ## Clients
        issuer: https://${ip_addr}:9000
        client:
          gateway-client:
            registration:
              client-id: "gateway-client"
              client-secret: ${client_secret}
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "https://${ip_addr}:8060/login/oauth2/code/gateway-client"
              post-logout-redirect-uris:
                - "https://${ip_addr}:8060/"
              scopes:
                - "openid"
                - "profile"
          android-client:
            registration:
              client-id: "android-client"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "com.example.myapp://oauth2redirect"
              post-logout-redirect-uris:
                - "https://${ip_addr}:8060/"
              scopes:
                - "openid"
                - "profile"

## Eureka Configurations
eureka:
  instance:
    secure-port: 9000
    secure-port-enabled: true
    non-secure-port-enabled: false

  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

## Authentication Token Properties
auth:
  token:
    scopes: openid, roles
    issuer: "https://${ip_addr}:9000"
    ## 2 Months
    expiration: 5_184_000

## Internal Communication Key
internal:
  communication-key: 308e813b6509dbef1efe8e673a5bc099


jwt:
  security:
    enabled: true
    publicPaths: /v3/api-docs/**, /swagger-ui/**, /swagger-ui.html, /auth/register


logging:
  level:
    org.springframework.security: trace