
server:
  port: 9000

cors:
  allowed-origins: http://localhost:3000, http://localhost:8060

spring:
  cloud:
    config:
      enabled: false
  application:
    name: authentication-server
  output:
    ansi:
      enabled: always

  ## Database Properties
  datasource:
    url: jdbc:postgresql://localhost:5454/e20
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  ## Security
  security:
    oauth2:
      authorizationserver: ## Clients
        client:
          gateway-client:
            registration:
              client-id: "gateway-client"
              client-secret: "$2a$12$oOagAoNYyMcpzY602Zqtj.YT/P1MuZUm/BraPQpHSNeWLIapyBOWq"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:8060/login/oauth2/code/gateway-client"
              post-logout-redirect-uris:
                - "http://localhost:8060/"
              scopes:
                - "openid"
                - "profile"
            # Tolgo il Consenso per il Profile
            # require-authorization-consent: true

## Eureka Configurations
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

## Authentication Token Properties
auth:
  token:
    scopes: openid, roles
    issuer: "http://127.0.0.1:9000"
    expiration: 3600

## Internal Communication Key
internal:
  communication-key: 308e813b6509dbef1efe8e673a5bc099


jwt:
  security:
    enabled: true
    publicPaths: /v3/api-docs/**, /swagger-ui/**, /swagger-ui.html, /auth/register


logging:
  level:
    org.springframework.security: trace