
server:
  port: 9000
  address: 0.0.0.0

spring:
  cloud:
    config:
      enabled: false
  application:
    name: authentication-server
  output:
    ansi:
      enabled: always

  ## Database Properties
  datasource:
    url: jdbc:postgresql://localhost:5454/e20
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  ## Security
  security:
    oauth2:
      authorizationserver: ## Clients
        client:
          gateway-client:
            registration:
              client-id: "gateway-client"
              client-secret: "$2a$12$oOagAoNYyMcpzY602Zqtj.YT/P1MuZUm/BraPQpHSNeWLIapyBOWq"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                -  "http://192.168.1.14:8060/login/oauth2/code/gateway-client"
              post-logout-redirect-uris:
                - "http://192.168.1.14:8060/"
              scopes:
                - "openid"
                - "profile"
          android-client:
            registration:
              client-id: "android-client"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "com.example.myapp://oauth2redirect"
              post-logout-redirect-uris:
                - "http://192.168.1.14:8060/"
              scopes:
                - "openid"
                - "profile"


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

## Authentication Token Properties
auth:
  token:
    scopes: openid, roles
    issuer: "http://192.168.1.14:9000"
    expiration: 3600


jwt:
  security:
    enabled: true
    publicPaths: /v3/api-docs/**, /swagger-ui/**, /swagger-ui.html, /auth/register

logging:
  level:
    org.springframework.security: trace