version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8085:8080"
    volumes:
      - ./realms:/opt/keycloak/data/import
    depends_on:
      - postgres
    # Usa `start` per applicare le migration su Postgres e poi importare il realm
    command:
      - start-dev
      - --import-realm
      - --http-enabled=true
      - --hostname-strict=false
    networks:
      - keycloak-network

volumes:
  postgres_data:

networks:
  keycloak-network:
